# Generated by Django 6.0.4 on 2026-04-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=255, unique=True, verbose_name='Unique nonce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Used Nonce',
                'verbose_name_plural': 'Used Nonces',
            },
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Vote Count'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_voted',
            field=models.BooleanField(default=False, verbose_name='Has Voted'),
        ),
        migrations.AddField(
            model_name='student',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='RSA Public Key'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_vote', models.TextField(verbose_name='Encrypted vote')),
                ('nonce', models.CharField(max_length=255, unique=True)),
                ('signature', models.TextField(verbose_name='Digital signature')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='auth_app.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='auth_app.student')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
