# Generated by Django 6.0.4 on 2026-04-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_usednonce_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(verbose_name='Server Private Key (PEM)')),
                ('public_key', models.TextField(verbose_name='Server Public Key (PEM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Server Key',
                'verbose_name_plural': 'Server Keys',
            },
        ),
    ]
