# Generated by Django 6.0.4 on 2026-04-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_serverkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='بداية التصويت')),
                ('end_time', models.DateTimeField(verbose_name='نهاية التصويت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الموعد',
                'verbose_name_plural': 'إعدادات الموعد',
            },
        ),
    ]
